"""sync_state_after_manual_fixes

Revision ID: 0b6765fc4f34
Revises: add_tiktok_platform
Create Date: 2026-03-30 11:58:48.529458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6765fc4f34'
down_revision: Union[str, Sequence[str], None] = 'add_tiktok_platform'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
