"""add category to seller_profiles

Revision ID: 1248d0241ad0
Revises: 0b6765fc4f34
Create Date: 2026-03-31 16:52:41.522130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1248d0241ad0'
down_revision: Union[str, Sequence[str], None] = '0b6765fc4f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'category')
    # ### end Alembic commands ###
