"""add trust_score to seller_profiles

Revision ID: 1728fb12475b
Revises: adbf45f3f944
Create Date: 2026-04-02 23:45:03.072167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1728fb12475b'
down_revision: Union[str, Sequence[str], None] = 'adbf45f3f944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('trust_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'trust_score')
    # ### end Alembic commands ###
